name: Artifact

on:
  workflow_dispatch:
  push:
jobs:
  build:
    strategy:
      matrix:
    env:
      DAY_OF_WEEK: Mon
    runs-on: [ubuntu-latest]
    
    steps:
#     - uses: actions/checkout@v2

    - name: Run a one-line script
      run: echo Hello ${{ github.event }} - ${{ env.DAY_OF_WEEK }} - ${{ job.container }} -${{ steps.test.conclusion }} from Octo Organization > artifact.txt
    
    - name: Run a another-line script
      run: echo Hello ${{ github.event11 }} from Octo Organization
      
    - name: Run a one-line script
      run: |
        echo Hello, world v1 after rerun!
        echo $GITHUB_RUN_ID
        echo $GITHUB_RUN_NUMBER
        echo $GITHUB_WORKFLOW
        echo $GITHUB_WORKFLOW_ID
        echo $GITHUB_WORKFLOW_NUMBER
      
    - uses: actions/upload-artifact@v2
      with:
        name: my-artifact-1
        path: artifact.txt
    - uses: actions/upload-artifact@v2
      with:
        name: my artifact & 2
        path: artifact.txt
