name: Artifact

on:
  workflow_dispatch:

jobs:
  build:
    needs: test
    runs-on: [ubuntu-latest]
    
    steps:
#     - uses: actions/checkout@v2
    
    - name: Run a one-line script
      run: echo Hello from Octo Organization > artifact.txt
    - uses: actions/upload-artifact@v2
      with:
        name: my-artifact-1
        path: artifact.txt
    - uses: actions/upload-artifact@v2
      with:
        name: my artifact & 2
        path: artifact.txt
