name: Caller JSONize
on:
  workflow_dispatch:
    inputs:
      to_jsonize:
        required: true
jobs:
  welcome_party:
    runs-on: ubuntu-latest
    steps:
    - run: echo "welcome to world of callable workflows"

  call_the_workflow:
    runs-on: ubuntu-latest
    needs: welcome_party
    uses: korea-dinos/ajaykn-public/.github/workflows/callable1.yml@main
    with:
      to_jsonize: ${{ github.event.inputs.to_jsonize }}
  
  goodbye_party:
    runs-on: ubuntu-latest
    needs: call_the_workflow
    steps:
    - run: echo "and we're done!"
