# This is a basic workflow to help you get started with Actions

name: Matrix

on:
  workflow_dispatch:
env:
  name: abc
jobs:
  build:
    name: test build
    strategy:
      matrix:
        os: [ubuntu-latest, macos-latest, windows-latest]
    runs-on: ${{ matrix.os }}
    steps:
      # Runs a single command using the runners shell
      - name: Run a one-line script ${{ env.name }}
        run: echo Hello, world!
  test:
    strategy:
      matrix:
        os: [ubuntu-latest, macos-latest, windows-latest]
        id: [1,2,3]
    runs-on: ${{ matrix.os }}
    steps:
      # Runs a single command using the runners shell
      - name: Run a one-line script-${{ matrix.id }}
        run: echo Hello, world!
