# This is a basic workflow to help you get started with Actions

name: Hello

on:
  workflow_dispatch:

jobs:
  build:
    matrix:
      os: [ubuntu-latest, macos-latest, windows-latest]
    runs-on: ${{ matrix.os }}
    steps:
      # Runs a single command using the runners shell
      - name: Run a one-line script
        run: echo Hello, world!
