name: Secrets
on:
  workflow_dispatch:

jobs:
  # This workflow contains a single job called "build"
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Print Secret
        run: |
          echo Print secret
          echo ${{ secrets.SECRET1 }}   
          echo Print secret in reverse
          echo '${{ secrets.SECRET1 }}' | rev
          echo ${{ secrets.SECRET1 }} >> log.txt
          cat log.txt

      # Runs a set of commands using the runners shell
#       - name: Run a multi-line script
#         env:
#           var1: val1
#           var2: ${{ secrets.SECRET1 }}
#         run: |
#           echo Add other actions to build,
#           echo test, and deploy your project.
#           echo ${{ env.var1 }}
#           echo '${{ secrets.GITHUB_TOKEN }}' | rev
#           echo ${{ env.var2 == 'secretval1' }}
#           echo '${{ env.var2 }}' | rev
#           echo secrets printed.
#       - name: test
#         env:
#           var1: ${{ secrets.SECRET1 }}
#         run: |
#           exit ${{ env.var1 == 'secretval1' }}
