# This is a basic workflow to help you get started with Actions


# Controls when the workflow will run
name: "[Test] braces"
on:
  push:
    branches:
      - "main"
    paths:
      - cloud/**
jobs:
  # This workflow contains a single job called "build"
  build:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:

      # Runs a set of commands using the runners shell
      - name: Run a multi-line script
        run: |
          echo Add other actions to build,
          echo test, and deploy your project.
